### ISSUE TITLE
New ARs not created

### ISSUE THREAD

**Issue by lemoene** [bikalabs/bika.lims#2161] opened 2017-08-02 20:04 UTC
I am not sure how this happened, see screenshots at https://jira.bikalabs.com/browse/LIMS-2685

## Steps to reproduce

Try to create 4 ARs inside a batch, 1 with AR Template, 1 with Profile, and 2 more with individually selected Analyses. see screenshots.

Press Save. While the form is saving and the spinner shown, click the lock or i icons on some of the selected Analyses (not sure whether this was the cause)

## Current behavior

The Spinner disappears but I was left on the AR Create form, and now new ARs created. Subsequent pressing of the Save button would just bring up the spinner for a while but nothing further happes

## Expected behavior

4 New ARs to be created

**Comment by lemoene** [comment] 2017-08-02 20:12
could not recreate it with a single ARs. Maybe the form did not fully load initially. I now see more complete messages when I click the lock icon. Will continue tomorrow

**Comment by ramonski** [comment] 2017-08-02 20:17
Thanks @lemoene  for testing.
Not reproducable on my side either.
Please try to capture a screenshot of the red lines in the Firefox JS Console if this error happens again. On FF this should open on pressing Ctrl+Shift+I or F12.

**Comment by ramonski** [comment] 2017-08-02 20:33
I'll close this one. Please re-open if it occurs again.

**Comment by ramonski** [comment] 2017-08-02 20:41
Ok, I could reproduce the issue and got the following traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.add2, line 46, in decorator
  Module bika.lims.browser.analysisrequest.add2, line 784, in __call__
  Module bika.lims.browser.analysisrequest.add2, line 1690, in ajax_submit
  Module bika.lims.utils.analysisrequest, line 81, in create_analysisrequest
  Module bika.lims.utils.sample, line 24, in create_sample
KeyError: 'SampleType'
```

**Comment by ramonski** [comment] 2017-08-02 20:43
Seems like the Copy button for the Sample Type field does not take over the hidden UID of the field. 

@lemoene: Please try to explicitly click on the Sample Type field and re-select the value. Does the error disappear?

**Comment by ramonski** [comment] 2017-08-02 20:47
Might be weird caching issues due to the multiple updates today – rebooting https://bikalims.ridingbytes.com

**Comment by ramonski** [comment] 2017-08-02 20:57
Seems to work after the server restart. Probably an artefact caused by the several server updates today.

**Closed by ramonski** 2017-08-02 20:57 UTC
