### ISSUE TITLE
Published Result portlet (Improvement Request)

### ISSUE THREAD

**Issue by eshiet** [bikalabs/bika.lims#2120] opened 2017-06-30 21:54 UTC
## Steps to reproduce
Nil
## Current behavior
Currently, there is no portlet displaying published result.

## Expected behavior
Since the following portlets are available: 
portlet_to_be_sampled
portlet_to_be_preserved
portlet_late_analyses
portlet_pending_orders
portlet_sample_due
portlet_to_be_verified
portlet_verified
I am suggesting that the following portlet is added:
portlet_scheduled sampling
portlet_received
portlet_published : this will enable the lab clerk to be able to see from the dashboard published result for possible printing.
portlet_rejected

**Comment by lemoene** [comment] 2017-07-01 12:29
What would the purpose of this portlet be Eshiet? Published ARs are always listed on the Published AR lists, in reverse chronological order latest at the top and the user is returned there immediately after publication. 

The alerts warn users to pending actions, to help labs cut down on turnaround and prevent ARs slipping through the cracks.

Keep them coming!

**Comment by eshiet** [comment] 2017-07-03 02:12
The purpose of this portlet is to enable the lab clerk to be able to know when a test result is ready. Its current location **" Published ARs are always listed on the Published AR lists, in reverse chronological order latest at the top and the user is returned there immediately after publication"**  will only make the lab clerk to go through at least 3 clicks to access the result in where it is currently stored. So if a widget is made for this, it will reduce the time the lab clerk will use to see the result and the lab clerk will be able to see published result for the day.

**Comment by lemoene** [comment] 2017-07-03 10:57
_The purpose of this portlet is to enable the lab clerk to be able to know when a test result is ready_

That is the purpose of the **_To be Verified_** portlet - it lists all ARs and WSs for which the results were captured and are ready for _Verification_.

There after ARs ready to be published appear in the **_Verified_** portlet. 

No need for more, andit is a 1 click operation in both cases. As this is not a bug or feature request, please move the discussion to the user list @eshiet. Closing it here

**Closed by lemoene** 2017-07-03 10:57 UTC

**Comment by eshiet** [comment] 2017-07-04 03:18
Okay Fine then.
